/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'Message'
 * message type.
 */

public class Message extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 12;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 10;

    /** Create a new Message of size 12. */
    public Message() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new Message of the given data_length. */
    public Message(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Message with the given data_length
     * and base offset.
     */
    public Message(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Message using the given byte array
     * as backing store.
     */
    public Message(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Message using the given byte array
     * as backing store, with the given base offset.
     */
    public Message(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Message using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public Message(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Message embedded in the given message
     * at the given base offset.
     */
    public Message(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Message embedded in the given message
     * at the given base offset and length.
     */
    public Message(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <Message> \n";
      try {
        s += "  [index=0x"+Long.toHexString(get_index())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nodeId=0x"+Long.toHexString(get_nodeId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [currentTime=0x"+Long.toHexString(get_currentTime())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [temperature=0x"+Long.toHexString(get_temperature())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [humidity=0x"+Long.toHexString(get_humidity())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [radiation=0x"+Long.toHexString(get_radiation())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: index
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'index' is signed (false).
     */
    public static boolean isSigned_index() {
        return false;
    }

    /**
     * Return whether the field 'index' is an array (false).
     */
    public static boolean isArray_index() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'index'
     */
    public static int offset_index() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'index'
     */
    public static int offsetBits_index() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'index'
     */
    public int get_index() {
        return (int)getUIntBEElement(offsetBits_index(), 16);
    }

    /**
     * Set the value of the field 'index'
     */
    public void set_index(int value) {
        setUIntBEElement(offsetBits_index(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'index'
     */
    public static int size_index() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'index'
     */
    public static int sizeBits_index() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodeId
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodeId' is signed (false).
     */
    public static boolean isSigned_nodeId() {
        return false;
    }

    /**
     * Return whether the field 'nodeId' is an array (false).
     */
    public static boolean isArray_nodeId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nodeId'
     */
    public static int offset_nodeId() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodeId'
     */
    public static int offsetBits_nodeId() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'nodeId'
     */
    public int get_nodeId() {
        return (int)getUIntBEElement(offsetBits_nodeId(), 16);
    }

    /**
     * Set the value of the field 'nodeId'
     */
    public void set_nodeId(int value) {
        setUIntBEElement(offsetBits_nodeId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'nodeId'
     */
    public static int size_nodeId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nodeId'
     */
    public static int sizeBits_nodeId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: currentTime
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'currentTime' is signed (false).
     */
    public static boolean isSigned_currentTime() {
        return false;
    }

    /**
     * Return whether the field 'currentTime' is an array (false).
     */
    public static boolean isArray_currentTime() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'currentTime'
     */
    public static int offset_currentTime() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'currentTime'
     */
    public static int offsetBits_currentTime() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'currentTime'
     */
    public int get_currentTime() {
        return (int)getUIntBEElement(offsetBits_currentTime(), 16);
    }

    /**
     * Set the value of the field 'currentTime'
     */
    public void set_currentTime(int value) {
        setUIntBEElement(offsetBits_currentTime(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'currentTime'
     */
    public static int size_currentTime() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'currentTime'
     */
    public static int sizeBits_currentTime() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: temperature
    //   Field type: int, unsigned
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'temperature' is signed (false).
     */
    public static boolean isSigned_temperature() {
        return false;
    }

    /**
     * Return whether the field 'temperature' is an array (false).
     */
    public static boolean isArray_temperature() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'temperature'
     */
    public static int offset_temperature() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'temperature'
     */
    public static int offsetBits_temperature() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'temperature'
     */
    public int get_temperature() {
        return (int)getUIntBEElement(offsetBits_temperature(), 16);
    }

    /**
     * Set the value of the field 'temperature'
     */
    public void set_temperature(int value) {
        setUIntBEElement(offsetBits_temperature(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'temperature'
     */
    public static int size_temperature() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'temperature'
     */
    public static int sizeBits_temperature() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: humidity
    //   Field type: int, unsigned
    //   Offset (bits): 64
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'humidity' is signed (false).
     */
    public static boolean isSigned_humidity() {
        return false;
    }

    /**
     * Return whether the field 'humidity' is an array (false).
     */
    public static boolean isArray_humidity() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'humidity'
     */
    public static int offset_humidity() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'humidity'
     */
    public static int offsetBits_humidity() {
        return 64;
    }

    /**
     * Return the value (as a int) of the field 'humidity'
     */
    public int get_humidity() {
        return (int)getUIntBEElement(offsetBits_humidity(), 16);
    }

    /**
     * Set the value of the field 'humidity'
     */
    public void set_humidity(int value) {
        setUIntBEElement(offsetBits_humidity(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'humidity'
     */
    public static int size_humidity() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'humidity'
     */
    public static int sizeBits_humidity() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: radiation
    //   Field type: int, unsigned
    //   Offset (bits): 80
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'radiation' is signed (false).
     */
    public static boolean isSigned_radiation() {
        return false;
    }

    /**
     * Return whether the field 'radiation' is an array (false).
     */
    public static boolean isArray_radiation() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'radiation'
     */
    public static int offset_radiation() {
        return (80 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'radiation'
     */
    public static int offsetBits_radiation() {
        return 80;
    }

    /**
     * Return the value (as a int) of the field 'radiation'
     */
    public int get_radiation() {
        return (int)getUIntBEElement(offsetBits_radiation(), 16);
    }

    /**
     * Set the value of the field 'radiation'
     */
    public void set_radiation(int value) {
        setUIntBEElement(offsetBits_radiation(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'radiation'
     */
    public static int size_radiation() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'radiation'
     */
    public static int sizeBits_radiation() {
        return 16;
    }

}
